"""Added small/big blinds to Url

Revision ID: 1b2f1e160adb
Revises: 8f210930f4f6
Create Date: 2022-08-07 08:42:55.796997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b2f1e160adb'
down_revision = '8f210930f4f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.add_column(sa.Column('small_blind', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('big_blind', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.drop_column('big_blind')
        batch_op.drop_column('small_blind')

    # ### end Alembic commands ###
