"""Adding last name for users

Revision ID: 34e65d2a4afc
Revises: ed2dd9b01055
Create Date: 2022-07-18 10:01:02.906897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34e65d2a4afc'
down_revision = 'ed2dd9b01055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_name')
    # ### end Alembic commands ###
