"""adding new records column to earnings

Revision ID: 3a6945dc55dd
Revises: df653d9a784c
Create Date: 2024-02-22 09:22:48.785185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a6945dc55dd'
down_revision = 'df653d9a784c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earning', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_record', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earning', schema=None) as batch_op:
        batch_op.drop_column('new_record')

    # ### end Alembic commands ###
