"""Added URL ID to Behavior

Revision ID: 451b2d13ee74
Revises: 6c3b2b6511d9
Create Date: 2022-08-04 17:08:47.115413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '451b2d13ee74'
down_revision = '6c3b2b6511d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('behavior', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_behavior_url_id_url'), 'url', ['url_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('behavior', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_behavior_url_id_url'), type_='foreignkey')
        batch_op.drop_column('url_id')

    # ### end Alembic commands ###
