"""Added subscription and expiration to User

Revision ID: 6263004d80e4
Revises: e80fdc3e0e02
Create Date: 2022-08-19 09:32:04.094966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6263004d80e4'
down_revision = 'e80fdc3e0e02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscribed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('expires_on', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('expires_on')
        batch_op.drop_column('subscribed')

    # ### end Alembic commands ###
