"""Adding Total buy-in amount for each game

Revision ID: 62fad94dca42
Revises: cba6b3727ff6
Create Date: 2022-07-25 15:37:41.028247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62fad94dca42'
down_revision = 'cba6b3727ff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('buyins', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'player', ['player_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('game', 'buyins')
    # ### end Alembic commands ###
