"""adding player gmae count

Revision ID: 6b731183b007
Revises: bea278044270
Create Date: 2022-07-13 16:33:13.289884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b731183b007'
down_revision = 'bea278044270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('games_played', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'games_played')
    # ### end Alembic commands ###
