"""Moved imported from Game to Url

Revision ID: 6c3b2b6511d9
Revises: 9d4f077d8044
Create Date: 2022-08-04 09:24:16.802343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c3b2b6511d9'
down_revision = '9d4f077d8044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('imported')

    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imported', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.drop_column('imported')

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imported', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
