"""Adding imported to Game

Revision ID: 701cc4187c28
Revises: a44aaaf0e843
Create Date: 2022-07-30 09:01:03.050958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701cc4187c28'
down_revision = 'a44aaaf0e843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imported', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('imported')

    # ### end Alembic commands ###
