"""Added duration played

Revision ID: 8f210930f4f6
Revises: 451b2d13ee74
Create Date: 2022-08-06 10:25:34.387997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f210930f4f6'
down_revision = '451b2d13ee74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('behavior', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hu_duration_played', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sr_duration_played', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ft_duration_played', sa.Integer(), nullable=True))

    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.drop_column('game_type')

    with op.batch_alter_table('behavior', schema=None) as batch_op:
        batch_op.drop_column('ft_duration_played')
        batch_op.drop_column('sr_duration_played')
        batch_op.drop_column('hu_duration_played')

    # ### end Alembic commands ###
