"""empty message

Revision ID: 9d4f077d8044
Revises: 0e0aa8f83551
Create Date: 2022-08-03 15:02:34.782940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d4f077d8044'
down_revision = '0e0aa8f83551'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('behavior', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hu_cbet_check_fold', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hu_2barrel_check_fold', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hu_3barrel_check_fold', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sr_cbet_check_fold', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sr_2barrel_check_fold', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sr_3barrel_check_fold', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ft_cbet_check_fold', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ft_2barrel_check_fold', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ft_3barrel_check_fold', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('behavior', schema=None) as batch_op:
        batch_op.drop_column('ft_3barrel_check_fold')
        batch_op.drop_column('ft_2barrel_check_fold')
        batch_op.drop_column('ft_cbet_check_fold')
        batch_op.drop_column('sr_3barrel_check_fold')
        batch_op.drop_column('sr_2barrel_check_fold')
        batch_op.drop_column('sr_cbet_check_fold')
        batch_op.drop_column('hu_3barrel_check_fold')
        batch_op.drop_column('hu_2barrel_check_fold')
        batch_op.drop_column('hu_cbet_check_fold')

    # ### end Alembic commands ###
