"""Changing back to numerics

Revision ID: b1cff83551af
Revises: f49c249d8414
Create Date: 2022-10-25 10:50:28.026325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1cff83551af'
down_revision = 'f49c249d8414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alias', schema=None) as batch_op:
        batch_op.drop_constraint('alias_alias_key', type_='unique')

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint('player_name_key', type_='unique')

    with op.batch_alter_table('pokernow_id', schema=None) as batch_op:
        batch_op.drop_constraint('pokernow_id_pn_id_key', type_='unique')

    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.drop_constraint('url_url_key', type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_email_key', ['email'])

    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.create_unique_constraint('url_url_key', ['url'])

    with op.batch_alter_table('pokernow_id', schema=None) as batch_op:
        batch_op.create_unique_constraint('pokernow_id_pn_id_key', ['pn_id'])

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.create_unique_constraint('player_name_key', ['name'])

    with op.batch_alter_table('alias', schema=None) as batch_op:
        batch_op.create_unique_constraint('alias_alias_key', ['alias'])

    # ### end Alembic commands ###
