"""test migration

Revision ID: bea278044270
Revises: db3266ff6a22
Create Date: 2022-07-13 15:14:48.553834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bea278044270'
down_revision = 'db3266ff6a22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('email', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'email')
    # ### end Alembic commands ###
