"""adding player_id and admin to users

Revision ID: cba6b3727ff6
Revises: 34e65d2a4afc
Create Date: 2022-07-21 14:17:06.538128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cba6b3727ff6'
down_revision = '34e65d2a4afc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('player_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'user', 'player', ['player_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'admin')
    op.drop_column('user', 'player_id')
    # ### end Alembic commands ###
