"""Added player_id to bankroll

Revision ID: e80fdc3e0e02
Revises: ddfaa9f03484
Create Date: 2022-08-08 11:14:05.987720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e80fdc3e0e02'
down_revision = 'ddfaa9f03484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bankroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_bankroll_player_id_player'), 'player', ['player_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bankroll', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_bankroll_player_id_player'), type_='foreignkey')
        batch_op.drop_column('player_id')

    # ### end Alembic commands ###
